### ISSUE TITLE
¿Is this an actual open source project?

### ISSUE THREAD

**Issue by Angel-del-dev** [GitHababi/C-Double-Flat#7]
I am a web developer with curiosity for this project.
If its possible and this project is open source, i could offer some help.

I've never programmed with c# but i am willing to learn if necessary. 
I can also write documentations so that other people know how to use the lang(both in English and Spanish), and/or try to create a website to display de lang, with a documentation, a brief explanation and a guide to install and use the lang.

In case this is not an open source project, i am going to watch the progress up close.

You've got a nice project right there, keep it up^^

**Comment by GitHababi** [comment]
You know I never really thought someone else would care too much for this little side project I have. Thanks for showing interest, you can of course contribute to the wiki and make pull requests and whatever else you want to! I really appreciate it!
