### ISSUE TITLE
I think i might be missing something

### ISSUE THREAD

**Issue by Angel-del-dev** [GitHababi/C-Double-Flat#8]
I've tryied executing the installer.iss, but 

its telling me this error, and the route its pointing to, does not exist,

![image](https://user-images.githubusercontent.com/60150253/182214268-154a0d34-c02d-463d-8dcc-e2ce73c311c4.png)

Ub C-Double-flat.App i only have a .csproj, an ico and Program.cs

**Comment by Angel-del-dev** [comment]
nvm, i didn't download the release exe

**Comment by GitHababi** [comment]
If you want to run the installer.iss make sure to Publish while in Visual Studio 2022. The .iss file generates the installer executable with the files generated.
